### ISSUE TITLE
Can not create sensor

### ISSUE THREAD

**Issue by semphos** [aws-samples/aws-appsync-iot-core-realtime-dashboard#1]
$ cd sensor
$ npm install
$ node create-sensor.js

**I am getting the following error after doing the commands given above:**

internal/modules/cjs/loader.js:979
  throw err;
  ^
Error: Cannot find module '~/aws-appsync-iot-core-realtime-dashboard/sensor/create-sensor.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by dave-moser** [comment]
Sorry - that is a typo in the instructions.  Sensors should be plural:

`$node create-sensors`

I'll update the docs.  Thanks for pointing this put.
